name: Zip Files

on: [push]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload release zip file
        uses: actions/upload-artifact@v2
        with:
          name: replay-buffer-notification
          path: |
            replay-buffer-with-notification.py
            ./assets
            README.md