name: Zip Files

on: [push]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: ./assets replay-buffer-with-notification.py
          dest: replay-buffer-notification.zip
      - name: Archive test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: replay-buffer-notification
          path: replay-buffer-notification.zip